### ISSUE TITLE
Instagram API information 

### ISSUE THREAD

**Issue by snew-lib** [bermud/geohealth-social#10]
Maryland

#opioidcrisis
opioid
Narcan
overdose

**Comment by nchavez1** [comment]
Information around instagram API use of location https://www.instagram.com/developer/endpoints/locations/

**Comment by nchavez1** [comment]
https://www.instagram.com/developer/authentication/
In reading through instagram's API documentation, I don't think we can get opioid (or any useful) data out of instagram because the posts (even if they are public) belong to the poster so we can't download post info in the same way that we can wit twitter. By default apps created for the Instagram API are in sandbox mode, and are only allowed to download the last 20 posts. They can also only access your user account and up to 9 other user accounts that accept your application request. So at most we can get the last 20 posts form 10 users and those 10 users actually have to agree to let us download it.
