### ISSUE TITLE
Geocoding of tweets

### ISSUE THREAD

**Issue by nchavez1** [bermud/geohealth-social#17]
I have been looking into how we can geocode data for the tweets and post where no explicit coordinates are available. In looking at geopandas http://geopy.readthedocs.io/en/1.11.0/ it seems like there would need to be a text source with the full address for the geocoding to be possible. I think the usual free geocoding services cannot geocode to the city/state.

Sara (or anyone) have you found any better information around this?

**Comment by tigerdolphins** [comment]
I was just looking over Akin's progress on the interface and he got the cluster feature working. I do however anticipate a problem with the locations of tweets. As you know, we will likely be coding tweets to the 'location' of a city rather than actual coordinates of the tweet itself. This is fine, but when you have multiple points exactly on top of eachother it becomes impossible to click on them individually and access information such as the tweet content. I see two approaches to dealing with this:
1)We don't care about being able to read the contents and metadata of tweets, since it is the clustering and distribution of different phrases that we actually care about
2)When assigning coordinates to a tweet a small amount of random variation should be introduced to put them in the right area but separate enough to click on them individually if you zoom in to an appropriate level.

**Comment by snew-lib** [comment]
Finished.  The script I used is in the Analytics folder - togeo_ProjectFinal.py

**Comment by snew-lib** [comment]
Updated script last night, files need to be re-run.
